import type { Metadata } from "next";
import "./globals.css";
import {Inter} from "next/font/google"
import { cn } from "@/lib/utils";
import Navbar from "@/components/homePage/Navbar";
const inter = Inter({subsets: ["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full" lang="en">
      <body className={cn("relative  font-sans antialiased", inter.className)}>
        <main className="relative items-center flex flex-col min-h-screen">
        {/* <Navbar /> */}
        <div className=" flex justify-center w-full h-full">
          {children}
        </div>
        </main>
      </body>
    </html>
  );
}
